name: Publish Docker Image
on: [ push, pull_request ]

jobs:
  build_image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    
    outputs:
      tag: ${{ steps.vars.outputs.tag }}

    strategy:
      matrix:
        arch:
          - 'import <nixpkgs> {}'
          - 'import <nixpkgs> { crossSystem.config = "aarch64-unknown-linux-gnu"; }'
            
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Get the version
        id: vars
        run: |
          tag="${GITHUB_REF:10}"
          if [[ "${tag}" == v* ]]; then
            echo ::set-output name=tag::$(echo "${tag}")
          else
            echo ::set-output name=tag::latest
          fi

      - name: Install nix
        uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-21.05
      - name: Build docker image
        env:
          tag: ${{ steps.vars.outputs.tag }}
        run: nix-build docker.nix --arg pkgs '${{ matrix.arch }}' --argstr tag $tag
        
      - name: Rename archive 
        run: mv result image.tar.gz
      - uses: actions/upload-artifact@master
        with:
          name: image
          path: image.tar.gz

